author: Ar7ific1al
description: Trap animal, player and monster souls in jars
main: com.github.ar7ific1al.souljars.Plugin
name: SoulJars
url: 
version: 0.1a
depend: [EnchantmentAPI]
commands:
    souljars:
        description: Base command for SoulJars
        usage: /<command>
permissions:
    place.holder.permission:
        description: Placeholder permissions
        default: op