author: Ar7ific1al
description: Soul Gems in Minecraft
main: com.github.ar7ific1al.soulgems.Plugin
name: SoulGems
url: 
version: 0.1a
commands:
    soulgems:
        description: Base command for SoulGems
        usage: /<command>
permissions:
    place.holder.permission:
        description: Placeholder permissions
        default: op